{% set name = "hdlib" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 669151da76285f425ae5d9cdd3e32fe68b550f9bfe4f630fd1a6b0f7c0e43fcd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy >=1.22.3
    - scikit-learn >=1.2.2
    - tabulate >=0.9.0

test:
  imports:
    - hdlib

about:
  home: https://github.com/cumbof/hdlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: hdlib
  description: |
    Hyperdimensional Computing Library for building Vector Symbolic Architectures in Python 3.

extra:
  recipe-maintainers:
    - cumbof
