{% set name = "hdlib" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5acb93ef9c42c48e7713ef0749de08b06e15d69c5dd60385efc386ce995f07f8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.22.3
    - scikit-learn >=1.2.2
    - tabulate >=0.9.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - hdlib

about:
  home: https://github.com/cumbof/hdlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: hdlib
  description: |
    Hyperdimensional Computing Library for building Vector Symbolic Architectures in Python 3.

extra:
  recipe-maintainers:
    - cumbof
