{% set name = "hdlib" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 595a918b8967f75bafe22f2492b0d12623cf2adda4d374ee656d8f8f9bba3f7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy >=1.22.3
    - scikit-learn >=1.2.2
    - tabulate >=0.9.0

test:
  imports:
    - hdlib

about:
  home: https://github.com/cumbof/hdlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: hdlib
  description: |
    Hyperdimensional Computing Library for building Vector Symbolic Architectures in Python 3.

extra:
  recipe-maintainers:
    - cumbof
