{% set name = "hdlib" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c49c23cfaa253f377f50d3dcca72467a2b35f776495d8199bf15794360d4f267

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy >=1.22.3
    - scikit-learn >=1.2.2
    - tabulate >=0.9.0

test:
  imports:
    - hdlib

about:
  home: https://github.com/cumbof/hdlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: hdlib
  description: |
    Hyperdimensional Computing Library for building Vector Symbolic Architectures in Python 3.

extra:
  recipe-maintainers:
    - cumbof
