{% set name = "hdlib" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75ac15d91b28a74b797fee248995f293748c1613ab8196ee7baeeaaf09ada92f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy >=1.22.3

test:
  imports:
    - hdlib

about:
  home: https://github.com/fabio-cumbo/hdlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: hdlib
  description: |
    Hyperdimensional Computing Library for building Vector Symbolic Architectures in Python 3.

extra:
  recipe-maintainers:
    - fabio-cumbo
